In [2]:
import numpy as np

# 1D Array

In [23]:
a = np.array([1,2])
a

array([1, 2])

# 2D Array

In [20]:
a1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# ndim -> gives the dimension of array

In [12]:
a1.ndim

2

In [14]:
a.ndim

1

# itemsize -> to know the size of each item in an array

In [18]:
a3.itemsize

8

In [21]:
a1.itemsize

8

In [25]:
a.itemsize

8

# dtype -> to know the data type of an array and also used for typecasting (changing the int array to float array)

In [26]:
a.dtype

dtype('int64')

In [27]:
a3.dtype

dtype('float64')

In [28]:
a4 = np.array([[1,2,3],[4,5,6]])
a4.dtype

dtype('int64')

In [36]:
a4 = np.array([[1,2,3],[4,5,6]], dtype = np.float64)
a4.dtype

dtype('float64')

# size -> Gives the total nuber of elements in an array

In [37]:
a.size

2

In [38]:
a1.size

9

In [40]:
a3.size

3

In [41]:
a4.size 

6

# shape -> GIves the number of rows and columns like (rows,columns)

In [42]:
a.shape

(2,)

In [49]:
a

array([1, 2])

In [43]:
a1.shape

(3, 3)

In [48]:
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
a3.shape

(3,)

In [45]:
a3

array([1. , 2.3, 3. ])

In [46]:
a4.shape

(2, 3)

In [47]:
a4

array([[1., 2., 3.],
       [4., 5., 6.]])

# zeros -> append the designed array with 0s with shape given like (2,3)

In [51]:
a5 = np.zeros((2,3), dtype = np.int)
a5

array([[0, 0, 0],
       [0, 0, 0]])

# ones -> append array with 1 with shape given like (3,3)

In [54]:
a6 = np.ones((6,6), dtype = np.int)
a6

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

# arange -> defines a range of numbers... Ceiling value or the max value entered is not counted in this

In [55]:
a7 = np.arange(0,10)
a7

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# linspace -> providing the number of digits specified within a range and the generated numbers are linealr spaced from each other

In [58]:
a8 = np.linspace(1,11,10)
a8

array([ 1.        ,  2.11111111,  3.22222222,  4.33333333,  5.44444444,
        6.55555556,  7.66666667,  8.77777778,  9.88888889, 11.        ])

# reshape -> change the shape of array like from(3,2) to (2,3)

In [63]:
a9 = np.array([[1,2],[3,4], [5,6]])


In [64]:
a9.shape

(3, 2)

In [65]:
a9.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [66]:
a9.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

# ravel -> it just flatten the n dimensional array to 1D array and does not make any changes in the original array. So if we want to store the result of the flatten array, then we will have to store it in a differnet variable.

In [67]:
a9

array([[1, 2],
       [3, 4],
       [5, 6]])

In [68]:
a9.ravel()

array([1, 2, 3, 4, 5, 6])

In [69]:
a9

array([[1, 2],
       [3, 4],
       [5, 6]])

In [70]:
b = a9.ravel()
b

array([1, 2, 3, 4, 5, 6])

In [71]:
a9

array([[1, 2],
       [3, 4],
       [5, 6]])

In [72]:
b

array([1, 2, 3, 4, 5, 6])

# min -> returns the minimum element, max -> returns the maximum element, sum -> returns the sum of the array

In [73]:
a9.min()

1

In [74]:
a9.max()

6

In [75]:
a9.min

<function ndarray.min>

In [76]:
a9.sum()

21

# axis -> defines the changes to m be made either in column or row; 0 : Columns, 1: Rows

In [77]:
a9

array([[1, 2],
       [3, 4],
       [5, 6]])

In [78]:
a9.sum(axis = 1)

array([ 3,  7, 11])

In [79]:
a9.sum(axis = 0)

array([ 9, 12])

# np.sqrt(object) -> gives square root of an array

In [80]:
np.sqrt(a9)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

# std -> returns the standard deviation

In [81]:
a9.std()

1.707825127659933

# operations in numpy arrays

In [93]:
array1 = np.array([[1,2], [4,5]])
array2 = np.array([[4,5], [7,8]])

In [86]:
array1+array2

array([[ 5,  7,  9],
       [11, 13, 15]])

In [87]:
array1-array2

array([[-3, -3, -3],
       [-3, -3, -3]])

In [88]:
array1*array2

array([[ 4, 10, 18],
       [28, 40, 54]])

In [90]:
array1/array2

array([[0.25      , 0.4       , 0.5       ],
       [0.57142857, 0.625     , 0.66666667]])

In [94]:
array1.dot(array2)

array([[18, 21],
       [51, 60]])